
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'try to add using FlutLab Firebase Configuration',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1nlbY1R5Gd3m2uG1PPqfTlDSCbspKUc',
    iosBundleId: 'com.pharghs.app',
    appId: '1:547113792974:ios:bafd52dcf222a920a5a79f',
    storageBucket: 'pharos-175a3.appspot.com',
    messagingSenderId: '547113792974',
    iosClientId: 'undefined',
    projectId: 'pharos-175a3'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLd46I4PP7IKaYAoAbiRK_6XgFuaBwYRY',
    appId: '1:547113792974:android:b949a56d78b25abea5a79f',
    messagingSenderId: '547113792974',
    projectId: 'pharos-175a3',
    storageBucket: 'pharos-175a3.appspot.com'
  );
}
